### ISSUE TITLE
Support for both LTS and latest node version?

### ISSUE THREAD

**Issue by Aliervo** [the-nix-way/dev-templates#10]
The node template is currently set to use version 18, which is the current LTS version of node (actually 18.16.0, but that's a nixpkgs channel cutoff issue).  It would be great to have a template for both LTS and the latest release, although I am not sure this is possible without switching to nixpkgs unstable/master.

Perhaps we could add an unstable input to the flake and use that explicitly?

**Comment by lucperkins** [comment]
I've now switched all the templates to use `nixpkgs-unstable` in #24
