### ISSUE TITLE
Mach nix is unmaintained

### ISSUE THREAD

**Issue by alper** [the-nix-way/dev-templates#21]
In the python dev template there's an inclusion of mach-nix: https://github.com/the-nix-way/dev-templates/blob/main/python/flake.nix#L7

This is an unmaintained project.

It's also not clear really why it should be there. The documentation for it is barely there.

**Comment by usrbinkat** [comment]
Reviewing, here is what I found.

1. [DavHau/mach-nix](https://github.com/DavHau/mach-nix), published it's 'unmaintained status' on [Dec 31 '22](https://github.com/DavHau/mach-nix/commit/68a85753555ed67ff53f0d0320e5ac3c725c7400)
2. News was published this week that [nix-community/dream2nix](https://github.com/nix-community/dream2nix/tree/main) is replacing [DavHau/mach-nix](https://github.com/DavHau/mach-nix)

I presume that either of the following actions needs to happen.

  1. [DavHau/mach-nix](https://github.com/DavHau/mach-nix) needs to be forked and maintained directly in this repo
  2. [dream2nix#python](https://github.com/nix-community/dream2nix/tree/main/templates/v1-python) should replace the use of [DavHau/mach-nix](https://github.com/DavHau/mach-nix) in this repo

**Comment by lucperkins** [comment]
Agreed that this should be removed. I'll have a look at alternatives and potentially add one later on.
