### ISSUE TITLE
difference with nix-flake-dev-environments

### ISSUE THREAD

**Issue by hatch01** [the-nix-way/dev-templates#29]
Hi, I don't really understand the difference between this repo and nix-flake-dev-environments.
They seem to deserve a pretty similar objective.
In my case, I set up a small shell function to be able to set up quickly dev env.
```shell
nix-quick () {
        nix flake new --template github:the-nix-way/dev-templates#$1 $2
}
```
Should I create two function for the two repos ?

**Comment by lucperkins** [comment]
The `nix-flake-dev-environments` repo provides fully functioning example projects in specific languages. The [Go](https://github.com/the-nix-way/nix-flake-dev-environments/tree/main/go), environment, for example, is an actual Go project. This repo is intended to provide [flake templates](https://zero-to-nix.com/concepts/flakes#templates) that you can use to drop a `flake.nix`/`flake.lock` into an existing project.
