### ISSUE TITLE
bun template not found

### ISSUE THREAD

**Issue by proehlen** [the-nix-way/dev-templates#51]
I'm trying to use the bun template with the following command:

```
nix flake init --template github:the-nix-way/dev-templates#bun
```

However it is producing this error:

```
error: flake 'github:the-nix-way/dev-templates' does not provide attribute 'templates.bun' or 'bun'
Did you mean cue?
```

To see if there was some problem with my environment, I tried to use `cue` with:

```
nix flake init --template github:the-nix-way/dev-templates#cue
```

And that produced output indicating success:

```
wrote: /home/p/Development/.envrc
wrote: /home/p/Development/flake.lock
wrote: /home/p/Development/flake.nix
```

I'm new to Nix and flakes, but it does appear that bun is missing from file: `https://github.com/the-nix-way/dev-templates/blob/main/flake.nix` even though there is a folder for it. bun is listed in the README so I assume it was intended that it be a supported option.

**Comment by lucperkins** [comment]
My bad! Fixed in 7f2ef8c
