### ISSUE TITLE
Java Template installs wrong JDK

### ISSUE THREAD

**Issue by vbrandl** [the-nix-way/dev-templates#55]
The [template for Java projects](https://github.com/the-nix-way/dev-templates/blob/main/java/flake.nix) seems to install the wrong JDK.

I'm using the following `flake.nix` on nixos/nixpkgs@a58bc8ad779655e790115244571758e8de055e3d:

```nix
{
  description = "A very basic flake";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
  };

  outputs = { self, nixpkgs }:
  let
    javaVersion = 22;
    supportedSystems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
    forEachSupportedSystem = f: nixpkgs.lib.genAttrs supportedSystems (system: f {
      pkgs = import nixpkgs { inherit system; };
    });
  in
  {
    overlays.default =
      final: prev: rec {
        jdk = prev."jdk${toString javaVersion}";
        maven = prev.maven.override { jre = jdk; };
      };

    devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.mkShell {
          packages = with pkgs; [ jdk maven ];
          MAVEN_OPTS = "--enable-preview";
        };
      });
  };
}
```

When I run `nix shell .\#devShells.x86_64-linux.default` (or activate the shell using direnv with `use flake`) and run `java --version`, I get `openjdk 21.0.3 2024-04-16` instead of the expected Java 22.

My guess is, this is using the `jdk` package from `nixpkgs`, which is Java 21, instead of the `jdk` package from the overlay, which should be Java 22.

I'm not quite sure how to tell my flake to use the overlay...

Edit: Merging #53, #54 applying [my comment](https://github.com/the-nix-way/dev-templates/pull/54#issuecomment-2286742714) from #54 seems to fix the issue for me.

**Comment by hatch01** [comment]
I am having the same issue, would love to see those PR merged
